[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tender = "GJe2DPcCBja5MLEenV2aeidsNxYavUMmA8eTJz8nSs9Z"

[programs.devnet]
tender = "GJe2DPcCBja5MLEenV2aeidsNxYavUMmA8eTJz8nSs9Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'tests TBD'"

[workspace]
members = ["programs/tender"]
