'use client';

/**
 * AI bid-comparison panel — renders inside BuyerBidDecryptionPanel after
 * the buyer has decrypted their bids. Sends the decrypted bids + the RFP
 * scope to the QVAC sidecar, renders a side-by-side comparison table +
 * recommended winner.
 *
 * Privacy: the request goes browser → QVAC sidecar directly. Decrypted
 * bid plaintexts never touch Tendr's backend. The little
 * "running on Tendr's QVAC sidecar" microcopy below the table makes
 * that explicit so the buyer can verify (or self-host the sidecar
 * to keep AI strictly local).
 */

import { CheckCircle2Icon, LoaderIcon, SparklesIcon } from 'lucide-react';
import { useState } from 'react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { type BidComparison, type CompareBidsValue, compareBids } from '@/lib/ai';
import { cn } from '@/lib/utils';

interface AiBidComparisonPanelProps {
  rfpScope: string;
  bids: Array<{
    bidIndex: number;
    bidPda: string;
    priceUsdc: string;
    timelineDays: number;
    scope: string;
    milestones: Array<{ name: string; amountUsdc: string; durationDays: number }>;
  }>;
  /** Optional: when the user clicks "Award this one" on the AI's
   *  recommendation, fire this with the winning bidPda so the parent
   *  can flip to the award confirmation flow. */
  onAwardRecommended?: (bidPda: string) => void;
}

export function AiBidComparisonPanel({
  rfpScope,
  bids,
  onAwardRecommended,
}: AiBidComparisonPanelProps) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<CompareBidsValue | null>(null);

  async function run() {
    setBusy(true);
    setError(null);
    setResult(null);
    try {
      const response = await compareBids({
        rfpScope,
        // Strip bidPda from the AI input — the model uses bidIndex
        // (positional). bidPda is for our UI use only.
        bids: bids.map(({ bidPda: _bidPda, ...rest }) => rest),
      });
      if (!response.ok) {
        setError(response.reason);
        return;
      }
      setResult(response.value);
    } finally {
      setBusy(false);
    }
  }

  if (!result && !busy && !error) {
    // Initial state: just the trigger button.
    return (
      <Button
        type="button"
        variant="outline"
        size="sm"
        className="gap-1.5 self-start"
        onClick={run}
      >
        <SparklesIcon className="size-3.5 text-primary" />
        Compare bids with AI
      </Button>
    );
  }

  return (
    <div className="flex flex-col gap-4 rounded-2xl border border-primary/30 bg-primary/[0.03] p-4">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <SparklesIcon className="size-4 text-primary" />
          <span className="font-display text-sm font-semibold">AI bid comparison</span>
        </div>
        {!busy && (
          <Button type="button" variant="ghost" size="sm" onClick={run}>
            Regenerate
          </Button>
        )}
      </div>

      {busy && (
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <LoaderIcon className="size-3.5 animate-spin" />
          Sending bids to the QVAC sidecar… first response may take a few seconds.
        </div>
      )}

      {error && <p className="text-xs text-destructive">{error}</p>}

      {result?.kind === 'parsed' && (
        <ParsedComparison
          comparison={result.comparison}
          bids={bids}
          onAwardRecommended={onAwardRecommended}
        />
      )}

      {result?.kind === 'raw' && (
        <div className="flex flex-col gap-2">
          <p className="text-[11px] text-amber-600 dark:text-amber-400">
            AI returned an unstructured response — showing it raw below. Try Regenerate
            for a structured comparison.
          </p>
          <pre className="overflow-auto rounded-lg border border-border/60 bg-card/40 p-3 font-mono text-[11px] leading-relaxed whitespace-pre-wrap">
            {result.text}
          </pre>
        </div>
      )}

      {result && (
        <p className="text-[11px] text-muted-foreground">
          Generated by Tendr's QVAC sidecar — local-first AI. Bids never left your browser
          for any third-party AI provider. See{' '}
          <a href="/docs/ai" className="underline underline-offset-2 hover:text-foreground">
            /docs/ai
          </a>{' '}
          for the data-flow detail.
        </p>
      )}
    </div>
  );
}

function ParsedComparison({
  comparison,
  bids,
  onAwardRecommended,
}: {
  comparison: BidComparison;
  bids: Array<{ bidIndex: number; bidPda: string }>;
  onAwardRecommended?: (bidPda: string) => void;
}) {
  const recommendedBidPda = bids.find((b) => b.bidIndex === comparison.recommendation.bidIndex)?.bidPda;
  return (
    <div className="flex flex-col gap-4">
      {/* Comparison table */}
      <div className="overflow-x-auto">
        <table className="w-full border-collapse text-xs">
          <thead>
            <tr className="border-b border-border/60 text-left text-[10px] uppercase tracking-wider text-muted-foreground">
              <th className="px-2 py-1.5">Bid</th>
              <th className="px-2 py-1.5 text-right">Price</th>
              <th className="px-2 py-1.5 text-right">Timeline</th>
              <th className="px-2 py-1.5 text-right">Milestones</th>
              <th className="px-2 py-1.5">Scope coverage</th>
              <th className="px-2 py-1.5">Milestones</th>
              <th className="px-2 py-1.5">Risk flags</th>
            </tr>
          </thead>
          <tbody>
            {comparison.rows.map((row) => {
              const isWinner = row.bidIndex === comparison.recommendation.bidIndex;
              return (
                <tr
                  key={row.bidIndex}
                  className={cn(
                    'border-b border-border/40',
                    isWinner && 'bg-primary/5',
                  )}
                >
                  <td className="px-2 py-2 align-top">
                    <div className="flex items-center gap-1.5">
                      <span className="font-mono">#{row.bidIndex + 1}</span>
                      {isWinner && (
                        <Badge variant="outline" className="gap-1 border-primary/40 text-primary">
                          <CheckCircle2Icon className="size-3" />
                          Pick
                        </Badge>
                      )}
                    </div>
                  </td>
                  <td className="px-2 py-2 text-right font-mono align-top tabular-nums">
                    ${row.priceUsdc}
                  </td>
                  <td className="px-2 py-2 text-right font-mono align-top tabular-nums">
                    {row.timelineDays}d
                  </td>
                  <td className="px-2 py-2 text-right font-mono align-top tabular-nums">
                    {row.milestoneCount}
                  </td>
                  <td className="px-2 py-2 align-top text-muted-foreground">
                    {row.scopeCoverage}
                  </td>
                  <td className="px-2 py-2 align-top text-muted-foreground">
                    {row.milestoneRealism}
                  </td>
                  <td className="px-2 py-2 align-top text-muted-foreground">
                    {row.riskFlags.length === 0 ? (
                      <span className="text-emerald-600 dark:text-emerald-400">none</span>
                    ) : (
                      <ul className="flex flex-col gap-0.5">
                        {row.riskFlags.map((flag) => (
                          <li key={flag} className="text-amber-600 dark:text-amber-400">
                            · {flag}
                          </li>
                        ))}
                      </ul>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Recommendation block */}
      <div className="flex flex-col gap-2 rounded-xl border border-primary/30 bg-card/40 p-3">
        <p className="text-[11px] font-medium uppercase tracking-wider text-primary">
          AI recommendation: bid #{comparison.recommendation.bidIndex + 1}
        </p>
        <p className="text-xs leading-relaxed">{comparison.recommendation.reasoning}</p>
        {onAwardRecommended && recommendedBidPda && (
          <Button
            type="button"
            size="sm"
            className="self-start gap-1.5"
            onClick={() => onAwardRecommended(recommendedBidPda)}
          >
            <CheckCircle2Icon className="size-3.5" />
            Award this bid
          </Button>
        )}
      </div>
    </div>
  );
}
